players:
  - "Chuck"
  - "Sarah"
  - "Casey"
  - "Morgan"
  - "Jeff"
  - "Lester"
  - "Devon"
  - "Ellie"
  - "Finch"
  - "Reese"
  - "Carter"
  - "Fusco"
  - "Root"
  - "Shaw"
  - "Elias"
  - "Greer"

models:
  - "openai/gpt-4.1"
  - "openai/o1"
  - "google/gemini-2.5-pro-preview"
  - "google/gemini-2.5-flash-preview-05-20:thinking"
  - "qwen/qwen3-32b"
  - "qwen/qwen3-235b-a22b"
  - "qwen/qwq-32b"
  - "anthropic/claude-3.7-sonnet"
  - "anthropic/claude-sonnet-4"
  - "anthropic/claude-opus-4"
  - "x-ai/grok-3-beta"
  - "x-ai/grok-3-mini-beta"
  - "meta-llama/llama-4-maverick"
  - "meta-llama/llama-4-scout"
  - "deepseek/deepseek-r1-0528"
  - "deepseek/deepseek-r1-0528-qwen3-8b"